version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - "${VITE_DOCKER_PORT_APP_DEV:-3004}:3004"